from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class Finding:
    rule: str
    display: str
    value: str
    masked: str
    span: tuple[int, int]
    file: Path | None = None
    line: int | None = None
    keypath: list = field(default_factory=list)


RULES: list[tuple[str, str, re.Pattern]] = [
    ("aws-access-key", "AWS access key",
        re.compile(r"\bAKIA[0-9A-Z]{16}\b")),
    ("aws-session-token", "AWS session token",
        re.compile(r"\bASIA[0-9A-Z]{16}\b")),
    ("github-pat", "GitHub PAT",
        re.compile(r"\bghp_[A-Za-z0-9]{36}\b")),
    ("github-oauth", "GitHub OAuth token",
        re.compile(r"\bgho_[A-Za-z0-9]{36}\b")),
    ("github-app", "GitHub App token",
        re.compile(r"\b(?:ghs|ghu)_[A-Za-z0-9]{36}\b")),
    ("github-fine-grained", "GitHub fine-grained PAT",
        re.compile(r"\bgithub_pat_[A-Za-z0-9_]{82}\b")),
    ("stripe-live", "Stripe live secret key",
        re.compile(r"\b(?:sk|rk)_live_[A-Za-z0-9]{24,}\b")),
    ("stripe-test", "Stripe test secret key",
        re.compile(r"\b(?:sk|rk)_test_[A-Za-z0-9]{24,}\b")),
    ("openai", "OpenAI API key",
        # (?!ant-) keeps this broad rule from shadowing Anthropic keys, which
        # would otherwise tie on span and win the overlap dedupe by list order.
        re.compile(r"\bsk-(?!ant-)(?:proj-)?[A-Za-z0-9_-]{40,}\b")),
    ("anthropic", "Anthropic API key",
        re.compile(r"\bsk-ant-(?:api|sid)[0-9]*-[A-Za-z0-9_-]{32,}\b")),
    ("google-api", "Google API key",
        re.compile(r"\bAIza[0-9A-Za-z_-]{35}\b")),
    ("slack-bot", "Slack bot token",
        re.compile(r"\bxoxb-[A-Za-z0-9-]{10,}\b")),
    ("slack-user", "Slack user token",
        re.compile(r"\bxoxp-[A-Za-z0-9-]{10,}\b")),
    ("slack-webhook", "Slack webhook URL",
        re.compile(r"https://hooks\.slack\.com/services/T[A-Z0-9]+/B[A-Z0-9]+/[A-Za-z0-9]+")),
    ("huggingface", "Hugging Face token",
        re.compile(r"\bhf_[A-Za-z0-9]{34}\b")),
    ("jwt", "JSON Web Token",
        re.compile(r"\beyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\b")),
    ("private-key-pem", "Private key (PEM block)",
        re.compile(r"-----BEGIN (?:RSA |EC |DSA |OPENSSH |PGP |ENCRYPTED )?PRIVATE KEY-----"
                   r"[\s\S]+?-----END (?:RSA |EC |DSA |OPENSSH |PGP |ENCRYPTED )?PRIVATE KEY-----")),
    ("db-url-with-password", "Database URL with password",
        re.compile(r"\b(?:postgres|postgresql|mysql|mongodb(?:\+srv)?|redis|amqp)://"
                   r"[^:/\s]+:[^@\s'\"]+@[^\s'\"/]+")),
    ("npm-token", "npm access token",
        re.compile(r"\bnpm_[A-Za-z0-9]{36}\b")),
    ("pypi-token", "PyPI upload token",
        re.compile(r"\bpypi-AgEIcHlwaS5vcmc[A-Za-z0-9_-]{50,}\b")),
    ("sendgrid", "SendGrid API key",
        re.compile(r"\bSG\.[A-Za-z0-9_-]{22}\.[A-Za-z0-9_-]{43}\b")),
    ("twilio", "Twilio API key",
        re.compile(r"\bSK[0-9a-fA-F]{32}\b")),
    # --- ported from gitleaks (see scripts/rules_drift.py mapping) ---
    ('1password-secret-key', '1Password secret key',
        re.compile('\\bA3-[A-Z0-9]{6}-(?:(?:[A-Z0-9]{11})|(?:[A-Z0-9]{6}-[A-Z0-9]{5}))-[A-Z0-9]{5}-[A-Z0-9]{5}-[A-Z0-9]{5}\\b')),
    ('1password-service-account-token', '1Password service account token',
        re.compile('\\bops_eyJ[a-zA-Z0-9+/]{250,}={0,3}')),
    ('adobe-client-secret', 'Adobe client secret',
        re.compile('\\bp8e-[a-zA-Z0-9]{32}\\b')),
    ('age-secret-key', 'age encryption secret key',
        re.compile('\\bAGE-SECRET-KEY-1[QPZRY9X8GF2TVDW0S3JN54KHCE6MUA7L]{58}\\b')),
    ('airtable-pat', 'Airtable personal access token',
        re.compile('\\bpat[A-Za-z0-9]{14}\\.[a-f0-9]{64}\\b')),
    ('alibaba-access-key-id', 'Alibaba Cloud AccessKey ID',
        re.compile('\\bLTAI[a-zA-Z0-9]{20}\\b')),
    ('anthropic-admin-key', 'Anthropic admin API key',
        re.compile('\\bsk-ant-admin01-[A-Za-z0-9_-]{93}AA\\b')),
    ('artifactory-api-key', 'Artifactory API key',
        re.compile('\\bAKCp[A-Za-z0-9]{69}\\b')),
    ('artifactory-reference-token', 'Artifactory reference token',
        re.compile('\\bcmVmd[A-Za-z0-9]{59}\\b')),
    ('atlassian-api-token', 'Atlassian API token',
        re.compile('\\bATATT3[A-Za-z0-9_=-]{186}(?![A-Za-z0-9_=-])')),
    ('authress-service-client-key', 'Authress service client access key',
        re.compile('\\b(?:sc|ext|scauth|authress)_[a-zA-Z0-9]{5,30}\\.[a-zA-Z0-9]{4,6}\\.acc[_-][a-zA-Z0-9-]{10,32}\\.[a-zA-Z0-9+/_=-]{30,120}(?![a-zA-Z0-9+/_=-])')),
    ('aws-bedrock-api-key-long-lived', 'AWS Bedrock API key (long-lived)',
        re.compile('\\bABSK[A-Za-z0-9+/]{109,269}={0,2}(?![A-Za-z0-9+/=])')),
    ('aws-bedrock-api-key-short-lived', 'AWS Bedrock API key (short-lived)',
        re.compile('\\bbedrock-api-key-YmVkcm9jay5hbWF6b25hd3MuY29t')),
    ('azure-ad-client-secret', 'Azure AD client secret',
        re.compile('(?<![a-zA-Z0-9_~.])[a-zA-Z0-9_~.]{3}\\dQ~[a-zA-Z0-9_~.-]{31,34}(?![a-zA-Z0-9_~.-])')),
    ('clickhouse-cloud-api-secret', 'ClickHouse Cloud API secret key',
        re.compile('\\b4b1d[A-Za-z0-9]{38}\\b')),
    ('clojars-api-token', 'Clojars API token',
        re.compile('(?i)\\bCLOJARS_[a-z0-9]{60}\\b')),
    ('cloudflare-origin-ca-key', 'Cloudflare Origin CA key',
        re.compile('\\bv1\\.0-[a-f0-9]{24}-[a-f0-9]{146}\\b')),
    # Gap between "curl" and the auth flag is bounded: gitleaks runs these on
    # RE2 (linear-time); Python's backtracking engine goes quadratic on
    # unbounded .* when a line mentions curl many times.
    ('curl-auth-header', 'curl Authorization header',
        re.compile('\\bcurl\\b(?:.{0,200}?|.{0,200}?(?:[\\r\\n]{1,2}.{0,200}?){1,5})[ \\t\\n\\r](?:-H|--header)(?:=|[ \\t]{0,5})(?:"(?i:Authorization:[ \\t]{0,5}(?:Basic[ \\t]([a-z0-9+/]{8,}={0,3})|(?:Bearer|(?:Api-)?Token)[ \\t]([\\w=~@.+/-]{8,})|([\\w=~@.+/-]{8,}))|(?:(?:X-(?:[a-z]+-)?)?(?:Api-?)?(?:Key|Token)):[ \\t]{0,5}([\\w=~@.+/-]{8,}))"|\'(?i:Authorization:[ \\t]{0,5}(?:Basic[ \\t]([a-z0-9+/]{8,}={0,3})|(?:Bearer|(?:Api-)?Token)[ \\t]([\\w=~@.+/-]{8,})|([\\w=~@.+/-]{8,}))|(?:(?:X-(?:[a-z]+-)?)?(?:Api-?)?(?:Key|Token)):[ \\t]{0,5}([\\w=~@.+/-]{8,}))\')(?:\\B|\\s|\\Z)')),
    ('curl-auth-user', 'curl basic auth credentials',
        re.compile('\\bcurl\\b(?:.{0,200}?|.{0,200}?(?:[\\r\\n]{1,2}.{0,200}?){1,5})[ \\t\\n\\r](?:-u|--user)(?:=|[ \\t]{0,5})("(:[^"]{3,}|[^:"]{3,}:|[^:"]{3,}:[^"]{3,})"|\'([^:\']{3,}:[^\']{3,})\'|((?:"[^"]{3,}"|\'[^\']{3,}\'|[\\w$@.-]+):(?:"[^"]{3,}"|\'[^\']{3,}\'|[\\w${}@.-]+)))(?=\\s|\\Z)')),
    ('databricks-api-token', 'Databricks API token',
        re.compile('\\bdapi[a-f0-9]{32}(?:-\\d)?\\b')),
    ('defined-networking-api-token', 'Defined Networking API token',
        re.compile('(?i)\\bdnkey-[a-z0-9=_-]{26}-[a-z0-9=_-]{52}(?=[\\x60\'"\\s;]|\\\\[nr]|$)')),
    ('digitalocean-access-token', 'DigitalOcean OAuth access token',
        re.compile('\\bdoo_v1_[a-f0-9]{64}\\b')),
    ('digitalocean-pat', 'DigitalOcean personal access token',
        re.compile('\\bdop_v1_[a-f0-9]{64}\\b')),
    ('digitalocean-refresh-token', 'DigitalOcean OAuth refresh token',
        re.compile('(?i)\\bdor_v1_[a-f0-9]{64}\\b')),
    ('doppler-api-token', 'Doppler API token',
        re.compile('\\bdp\\.pt\\.(?i:[a-z0-9]{43})\\b')),
    ('duffel-api-token', 'Duffel API token',
        re.compile('\\bduffel_(?:test|live)_(?i:[a-z0-9_=-]{43})')),
    ('dynatrace-api-token', 'Dynatrace API token',
        re.compile('\\bdt0c01\\.(?i:[a-z0-9]{24}\\.[a-z0-9]{64})\\b')),
    ('easypost-api-token', 'EasyPost API token',
        re.compile('\\bEZAK(?i:[a-z0-9]{54})\\b')),
    ('easypost-test-api-token', 'EasyPost test API token',
        re.compile('\\bEZTK(?i:[a-z0-9]{54})\\b')),
    # gitleaks' facebook-access-token (digits|secret) is omitted: upstream
    # relies on an entropy gate to stay precise; without one it matches any
    # pipe-delimited log line with a microsecond timestamp.
    ('facebook-page-token', 'Facebook page access token',
        re.compile('\\bEAA[MC][A-Za-z0-9]{100,}\\b')),
    ('flutterwave-encryption-key', 'Flutterwave encryption key',
        re.compile('\\bFLWSECK_TEST-(?i:[a-h0-9]{12})\\b')),
    ('flutterwave-public-key', 'Flutterwave public key',
        re.compile('\\bFLWPUBK_TEST-(?i:[a-h0-9]{32}-x)\\b')),
    ('flutterwave-secret-key', 'Flutterwave secret key',
        re.compile('\\bFLWSECK_TEST-(?i:[a-h0-9]{32}-x)\\b')),
    ('flyio-token', 'Fly.io access token',
        re.compile('\\b(?:fo1_[\\w-]{43}|fm1[ar]_[A-Za-z0-9+/]{100,}={0,3}|fm2_[A-Za-z0-9+/]{100,}={0,3})(?![\\w+/=-])')),
    ('frameio-token', 'Frame.io API token',
        re.compile('\\bfio-u-[A-Za-z0-9_=-]{64}(?![\\w=-])')),
    ('github-refresh-token', 'GitHub refresh token',
        re.compile('\\bghr_[A-Za-z0-9]{36}\\b')),
    ('gitlab-cicd-job-token', 'GitLab CI/CD job token',
        re.compile('\\bglcbt-[0-9a-zA-Z]{1,5}_[0-9a-zA-Z_-]{20}(?![\\w-])')),
    ('gitlab-deploy-token', 'GitLab deploy token',
        re.compile('\\bgldt-[0-9a-zA-Z_-]{20}(?![\\w-])')),
    ('gitlab-feature-flag-client-token', 'GitLab feature flag client token',
        re.compile('\\bglffct-[0-9a-zA-Z_-]{20}(?![\\w-])')),
    ('gitlab-feed-token', 'GitLab feed token',
        re.compile('\\bglft-[0-9a-zA-Z_-]{20}(?![\\w-])')),
    ('gitlab-incoming-mail-token', 'GitLab incoming mail token',
        re.compile('\\bglimt-[0-9a-zA-Z_-]{25}(?![\\w-])')),
    ('gitlab-kubernetes-agent-token', 'GitLab Kubernetes agent token',
        re.compile('\\bglagent-[0-9a-zA-Z_-]{50}(?![\\w-])')),
    ('gitlab-oauth-app-secret', 'GitLab OAuth application secret',
        re.compile('\\bgloas-[0-9a-zA-Z_-]{64}(?![\\w-])')),
    ('gitlab-pat', 'GitLab personal access token',
        re.compile('\\bglpat-[\\w-]{20}(?![\\w-])')),
    ('gitlab-pat-routable', 'GitLab personal access token (routable)',
        re.compile('\\bglpat-[0-9A-Za-z_-]{27,300}\\.[0-9a-z]{9}\\b')),
    ('gitlab-pipeline-trigger', 'GitLab pipeline trigger token',
        re.compile('\\bglptt-[0-9a-f]{40}\\b')),
    ('gitlab-runner-registration', 'GitLab runner registration token',
        re.compile('\\bGR1348941[0-9A-Za-z_-]{20}\\b')),
    ('gitlab-runner-auth', 'GitLab runner authentication token',
        re.compile('\\bglrt-[0-9A-Za-z_-]{20}\\b')),
    ('gitlab-runner-auth-routable', 'GitLab runner authentication token (routable)',
        re.compile('\\bglrt-t\\d_[0-9A-Za-z_-]{27,300}\\.[0-9a-z]{9}\\b')),
    ('gitlab-scim', 'GitLab SCIM token',
        re.compile('\\bglsoat-[0-9A-Za-z_-]{20}\\b')),
    ('gitlab-session-cookie', 'GitLab session cookie',
        re.compile('\\b_gitlab_session=[0-9a-z]{32}\\b')),
    ('grafana-api-key', 'Grafana API key',
        re.compile('\\beyJrIjoi[A-Za-z0-9]{70,400}={0,3}')),
    ('grafana-cloud-token', 'Grafana Cloud API token',
        re.compile('\\bglc_[A-Za-z0-9+/]{32,400}={0,3}')),
    ('grafana-service-account', 'Grafana service account token',
        re.compile('\\bglsa_[A-Za-z0-9]{32}_[0-9a-fA-F]{8}\\b')),
    ('harness', 'Harness access token (PAT/SAT)',
        re.compile('\\b(?:pat|sat)\\.[A-Za-z0-9_-]{22}\\.[A-Za-z0-9]{24}\\.[A-Za-z0-9]{20}\\b')),
    ('terraform-api-token', 'HashiCorp Terraform Cloud API token',
        re.compile('\\b[A-Za-z0-9]{14}\\.atlasv1\\.[A-Za-z0-9_=-]{60,70}\\b')),
    ('heroku-api-key', 'Heroku API key',
        re.compile('\\bHRKU-AA[0-9A-Za-z_-]{58}\\b')),
    ('huggingface-org', 'Hugging Face organization API token',
        re.compile('\\bapi_org_[A-Za-z]{34}\\b')),
    ('infracost', 'Infracost API token',
        re.compile('\\bico-[A-Za-z0-9]{32}\\b')),
    ('intra42-client-secret', 'Intra42 client secret',
        re.compile('\\bs-s4t2(?:ud|af)-[a-fA-F0-9]{64}\\b')),
    ('jwt-base64', 'JSON Web Token (base64-encoded)',
        re.compile('\\bZXlK(?:(?P<alg>aGJHY2lPaU)|(?P<apu>aGNIVWlPaU)|(?P<apv>aGNIWWlPaU)|(?P<aud>aGRXUWlPaU)|(?P<b64>aU5qUWlP)|(?P<crit>amNtbDBJanBi)|(?P<cty>amRIa2lPaU)|(?P<epk>bGNHc2lPbn)|(?P<enc>bGJtTWlPaU)|(?P<jku>cWEzVWlPaU)|(?P<jwk>cWQyc2lPb)|(?P<iss>cGMzTWlPaU)|(?P<iv>cGRpSTZJ)|(?P<kid>cmFXUWlP)|(?P<key_ops>clpYbGZiM0J6SWpwY)|(?P<kty>cmRIa2lPaUp)|(?P<nonce>dWIyNWpaU0k2)|(?P<p2c>d01tTWlP)|(?P<p2s>d01uTWlPaU)|(?P<ppt>d2NIUWlPaU)|(?P<sub>emRXSWlPaU)|(?P<svt>emRuUWlP)|(?P<tag>MFlXY2lPaU)|(?P<typ>MGVYQWlPaUp)|(?P<url>MWNtd2l)|(?P<use>MWMyVWlPaUp)|(?P<ver>MlpYSWlPaU)|(?P<version>MlpYSnphVzl1SWpv)|(?P<x>NElqb2)|(?P<x5c>NE5XTWlP)|(?P<x5t>NE5YUWlPaU)|(?P<x5ts256>NE5YUWpVekkxTmlJNkl)|(?P<x5u>NE5YVWlPaU)|(?P<zip>NmFYQWlPaU))[a-zA-Z0-9\\/\\\\_+\\-\\r\\n]{40,}={0,2}')),
    ('linear-api-key', 'Linear API key',
        re.compile('\\blin_api_[A-Za-z0-9]{40}\\b')),
    ('mailgun-private-token', 'Mailgun private API token',
        re.compile('(?i)[\\w.-]{0,50}?(?:mailgun)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(key-[a-f0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)')),
    ('mailgun-public-key', 'Mailgun public validation key',
        re.compile('(?i)[\\w.-]{0,50}?(?:mailgun)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}(pubkey-[a-f0-9]{32})(?:[\\x60\'"\\s;]|\\\\[nr]|$)')),
    ('mailgun-signing-key', 'Mailgun webhook signing key',
        re.compile('(?i)[\\w.-]{0,50}?(?:mailgun)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}([a-h0-9]{32}-[a-h0-9]{8}-[a-h0-9]{8})(?:[\\x60\'"\\s;]|\\\\[nr]|$)')),
    ('mapbox-api-token', 'Mapbox API token',
        re.compile('\\bpk\\.[a-zA-Z0-9]{60}\\.[a-zA-Z0-9]{22}\\b')),
    ('maxmind-license-key', 'MaxMind license key',
        re.compile('\\b[A-Za-z0-9]{6}_[A-Za-z0-9]{29}_mmk\\b')),
    ('microsoft-teams-webhook', 'Microsoft Teams incoming webhook URL',
        re.compile('https://[a-z0-9]+\\.webhook\\.office\\.com/webhookb2/[a-z0-9]{8}-(?:[a-z0-9]{4}-){3}[a-z0-9]{12}@[a-z0-9]{8}-(?:[a-z0-9]{4}-){3}[a-z0-9]{12}/IncomingWebhook/[a-z0-9]{32}/[a-z0-9]{8}-(?:[a-z0-9]{4}-){3}[a-z0-9]{12}')),
    ('new-relic-browser-token', 'New Relic ingest browser API token',
        re.compile('\\bNRJS-[a-fA-F0-9]{19}\\b')),
    ('new-relic-insert-key', 'New Relic insights insert key',
        re.compile('\\bNRII-[A-Za-z0-9-]{32}\\b')),
    ('new-relic-user-key', 'New Relic user API key',
        re.compile('\\bNRAK-[A-Za-z0-9]{27}\\b')),
    ('notion-api-token', 'Notion API token',
        re.compile('\\bntn_[0-9]{11}[A-Za-z0-9]{35}\\b')),
    # Digit lookahead stands in for gitleaks' entropy gate: real keys are
    # random base32-ish; SCREAMING_CASE words like API-TIMEOUTBUDGETEXCEEDED
    # contain no digits.
    ('octopus-deploy-api-key', 'Octopus Deploy API key',
        re.compile('\\bAPI-(?=[A-Z0-9]*[0-9])[A-Z0-9]{26}\\b')),
    ('openshift-user-token', 'OpenShift user token',
        re.compile('\\bsha256~[\\w-]{43}(?![\\w-])')),
    ('perplexity-api-key', 'Perplexity API key',
        re.compile('\\bpplx-[A-Za-z0-9]{48}\\b')),
    ('plaid-access-token', 'Plaid access token',
        re.compile('\\baccess-(?:sandbox|development|production)-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\\b')),
    ('planetscale-api-token', 'PlanetScale API token',
        re.compile('\\bpscale_tkn_[\\w=.\\-]{32,64}(?![\\w=.\\-])')),
    ('planetscale-oauth-token', 'PlanetScale OAuth token',
        re.compile('\\bpscale_oauth_[\\w=.\\-]{32,64}(?![\\w=.\\-])')),
    ('planetscale-password', 'PlanetScale database password',
        re.compile('\\bpscale_pw_[\\w=.\\-]{32,64}(?![\\w=.\\-])')),
    ('postman-api-key', 'Postman API key',
        re.compile('\\bPMAK-[a-fA-F0-9]{24}-[a-fA-F0-9]{34}\\b')),
    ('prefect-api-key', 'Prefect API key',
        re.compile('\\bpnu_[A-Za-z0-9]{36}\\b')),
    ('pulumi-access-token', 'Pulumi access token',
        re.compile('\\bpul-[a-f0-9]{40}\\b')),
    ('readme-api-token', 'ReadMe API token',
        re.compile('\\brdme_[a-z0-9]{70}\\b')),
    ('rubygems-api-key', 'RubyGems API key',
        re.compile('\\brubygems_[a-f0-9]{48}\\b')),
    ('scalingo-api-token', 'Scalingo API token',
        re.compile('\\btk-us-[\\w-]{48}(?![\\w-])')),
    ('sendinblue-api-key', 'Sendinblue (Brevo) API key',
        re.compile('\\bxkeysib-[a-f0-9]{64}-[A-Za-z0-9]{16}\\b')),
    ('sentry-org-token', 'Sentry organization auth token',
        re.compile('\\bsntrys_eyJpYXQiO[a-zA-Z0-9+/]{10,200}(?:LCJyZWdpb25fdXJs|InJlZ2lvbl91cmwi|cmVnaW9uX3VybCI6)[a-zA-Z0-9+/]{10,200}={0,2}_[a-zA-Z0-9+/]{43}(?![a-zA-Z0-9+/])')),
    ('sentry-user-token', 'Sentry user auth token',
        re.compile('\\bsntryu_[a-f0-9]{64}\\b')),
    ('settlemint-app-token', 'SettleMint application access token',
        re.compile('\\bsm_aat_[A-Za-z0-9]{16}\\b')),
    ('settlemint-pat', 'SettleMint personal access token',
        re.compile('\\bsm_pat_[A-Za-z0-9]{16}\\b')),
    ('settlemint-sat', 'SettleMint service access token',
        re.compile('\\bsm_sat_[A-Za-z0-9]{16}\\b')),
    ('shippo', 'Shippo API token',
        re.compile('\\bshippo_(?:live|test)_[a-fA-F0-9]{40}\\b')),
    ('shopify-access-token', 'Shopify access token',
        re.compile('\\bshpat_[a-fA-F0-9]{32}\\b')),
    ('shopify-custom-access-token', 'Shopify custom app access token',
        re.compile('\\bshpca_[a-fA-F0-9]{32}\\b')),
    ('shopify-private-app-token', 'Shopify private app access token',
        re.compile('\\bshppa_[a-fA-F0-9]{32}\\b')),
    ('shopify-shared-secret', 'Shopify shared secret',
        re.compile('\\bshpss_[a-fA-F0-9]{32}\\b')),
    ('sidekiq-secret', 'Sidekiq Enterprise credential',
        re.compile('(?i)[\\w.-]{0,50}?(?:BUNDLE_ENTERPRISE__CONTRIBSYS__COM|BUNDLE_GEMS__CONTRIBSYS__COM)(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}[a-f0-9]{8}:[a-f0-9]{8}(?:[\\x60\'"\\s;]|\\\\[nr]|$)')),
    ('sidekiq-sensitive-url', 'Sidekiq Enterprise gem URL with credentials',
        re.compile('(?i)\\bhttps?://[a-f0-9]{8}:[a-f0-9]{8}@(?:gems|enterprise)\\.contribsys\\.com\\b')),
    ('slack-app-token', 'Slack app-level token',
        re.compile('(?i)\\bxapp-\\d-[A-Z0-9]+-\\d+-[a-z0-9]+\\b')),
    ('slack-config-access-token', 'Slack configuration access token',
        re.compile('(?i)\\bxoxe\\.xox[bp]-\\d-[A-Z0-9]{163,166}\\b')),
    ('slack-config-refresh-token', 'Slack configuration refresh token',
        re.compile('(?i)\\bxoxe-\\d-[A-Z0-9]{146}\\b')),
    ('slack-legacy-token', 'Slack legacy token',
        re.compile('\\bxox[os]-\\d+-\\d+-\\d+-[a-fA-F0-9]+\\b')),
    ('slack-legacy-workspace-token', 'Slack legacy workspace token',
        re.compile('\\bxox[ar]-(?:\\d-)?[0-9a-zA-Z]{8,48}\\b')),
    ('snyk', 'Snyk API token',
        re.compile('(?i)[\\w.-]{0,50}?(?:snyk[_.-]?(?:(?:api|oauth)[_.-]?)?(?:key|token))(?:[ \\t\\w.-]{0,20})[\\s\'"]{0,3}(?:=|>|:{1,3}=|\\|\\||:|=>|\\?=|,)[\\x60\'"\\s=]{0,5}[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}(?:[\\x60\'"\\s;]|\\\\[nr]|$)')),
    # EAAA branch requires a digit and a lowercase char (gitleaks uses an
    # entropy gate): base64 of zero-padded binary encodes to 'EAAAAA...'.
    ('square-access-token', 'Square access token',
        re.compile('\\b(?:EAAA(?=[\\w-]{0,60}[0-9])(?=[\\w-]{0,60}[a-z])|sq0atp-)'
                   '[\\w-]{22,60}(?![\\w-])')),
    ('telegram-bot-token', 'Telegram bot token',
        re.compile('\\b\\d{5,16}:A[A-Za-z0-9_-]{34}(?![A-Za-z0-9_-])')),
    ('typeform-token', 'Typeform API token',
        re.compile('\\btfp_[A-Za-z0-9_.=-]{59}(?![A-Za-z0-9_.=-])')),
    ('vault-batch-token', 'HashiCorp Vault batch token',
        re.compile('\\bhvb\\.[\\w-]{138,300}(?![\\w-])')),
    # Legacy 's.<24>' branch dropped (gitleaks keeps it behind an entropy
    # gate): it matches any single-letter variable followed by a 24-char
    # method/attribute name. hvs. covers every token since Vault 1.10.
    ('vault-service-token', 'HashiCorp Vault service token',
        re.compile('\\bhvs\\.[\\w-]{90,120}(?![\\w-])')),
]


def mask(secret: str) -> str:
    if len(secret) <= 12:
        return secret[:3] + "*" * max(0, len(secret) - 3)
    return secret[:6] + "*" * 8 + secret[-4:]


def scan_text(text: str) -> list[Finding]:
    findings: list[Finding] = []
    for rule_id, display, pattern in RULES:
        for m in pattern.finditer(text):
            val = m.group(0)
            findings.append(Finding(
                rule=rule_id,
                display=display,
                value=val,
                masked=mask(val),
                span=(m.start(), m.end()),
            ))
    findings.sort(key=lambda f: f.span[0])
    return _dedupe_overlapping(findings)


def _dedupe_overlapping(findings: list[Finding]) -> list[Finding]:
    if not findings:
        return findings
    out = [findings[0]]
    for f in findings[1:]:
        last = out[-1]
        if f.span[0] < last.span[1]:
            if (f.span[1] - f.span[0]) > (last.span[1] - last.span[0]):
                out[-1] = f
            continue
        out.append(f)
    return out


ROTATION_GUIDANCE: dict[str, str] = {
    "aws-access-key": "Rotate: aws iam create-access-key, then aws iam delete-access-key --access-key-id <ID>",
    "aws-session-token": "Session tokens are short-lived; rotate the underlying IAM role/user credentials.",
    "github-pat": "Revoke: https://github.com/settings/tokens",
    "github-oauth": "Revoke: https://github.com/settings/applications",
    "github-app": "Rotate via your GitHub App's settings page.",
    "github-fine-grained": "Revoke: https://github.com/settings/tokens?type=beta",
    "stripe-live": "Roll: https://dashboard.stripe.com/apikeys",
    "stripe-test": "Roll: https://dashboard.stripe.com/test/apikeys",
    "openai": "Revoke: https://platform.openai.com/api-keys",
    "anthropic": "Revoke: https://console.anthropic.com/settings/keys",
    "google-api": "Rotate: https://console.cloud.google.com/apis/credentials",
    "slack-bot": "Rotate: https://api.slack.com/apps (OAuth & Permissions)",
    "slack-user": "Rotate: https://api.slack.com/apps (OAuth & Permissions)",
    "slack-webhook": "Regenerate the webhook in the Slack app that owns it.",
    "huggingface": "Revoke: https://huggingface.co/settings/tokens",
    "jwt": "Invalidate at the issuing service; short-lived tokens may expire naturally.",
    "private-key-pem": "Regenerate the key pair and rotate any authorized_keys / cert stores that reference it.",
    "db-url-with-password": "Change the database user's password and update connection strings.",
    "npm-token": "Revoke: https://www.npmjs.com/settings/~/tokens",
    "pypi-token": "Revoke: https://pypi.org/manage/account/token/",
    "sendgrid": "Rotate: https://app.sendgrid.com/settings/api_keys",
    "twilio": "Rotate: https://console.twilio.com/us1/account/keys-credentials/api-keys",
    # --- ported from gitleaks (see scripts/rules_drift.py mapping) ---
    '1password-secret-key': 'Rotate: regenerate the Secret Key in your 1Password account profile (https://support.1password.com/secret-key/)',
    '1password-service-account-token': 'Revoke: https://my.1password.com/developer (Service Accounts > revoke token)',
    'adobe-client-secret': 'Rotate: https://developer.adobe.com/console (Project > Credentials > rotate client secret)',
    'age-secret-key': 'Rotate: generate a new key with `age-keygen` and re-encrypt affected files; age keys cannot be remotely revoked.',
    'airtable-pat': 'Revoke: https://airtable.com/create/tokens',
    'alibaba-access-key-id': 'Rotate: https://ram.console.aliyun.com/manage/ak (disable, then delete the AccessKey pair)',
    'anthropic-admin-key': 'Revoke: https://console.anthropic.com/settings/admin-keys',
    'artifactory-api-key': 'Revoke: your Artifactory instance > Edit Profile > revoke API key (deprecated; or DELETE /api/security/apiKey)',
    'artifactory-reference-token': 'Revoke: JFrog Platform > Administration > User Management > Access Tokens (or DELETE /access/api/v1/tokens/<id>)',
    'atlassian-api-token': 'Revoke: https://id.atlassian.com/manage-profile/security/api-tokens',
    'authress-service-client-key': 'Rotate: https://authress.io/app (Service Clients > rotate access key)',
    'aws-bedrock-api-key-long-lived': 'Revoke: https://console.aws.amazon.com/iam/ (Users > Security credentials > delete the Amazon Bedrock API key)',
    'aws-bedrock-api-key-short-lived': 'Short-lived Bedrock API keys expire automatically (max 12h); revoke the underlying IAM session/credentials if compromised.',
    'azure-ad-client-secret': 'Rotate: https://portal.azure.com (Microsoft Entra ID > App registrations > Certificates & secrets)',
    'clickhouse-cloud-api-secret': 'Rotate: https://console.clickhouse.cloud (organization Settings > API Keys)',
    'clojars-api-token': 'Revoke: https://clojars.org/tokens',
    'cloudflare-origin-ca-key': 'Rotate: https://dash.cloudflare.com/profile/api-tokens (Origin CA Key)',
    'curl-auth-header': 'Rotate the exposed header credential at its issuing service; it was passed on the command line.',
    'curl-auth-user': 'Change the password at the target service; basic-auth credentials were passed on the command line.',
    'databricks-api-token': 'Revoke: Databricks workspace > Settings > Developer > Access tokens (or `databricks tokens delete --token-id <ID>`)',
    'defined-networking-api-token': 'Revoke: https://admin.defined.net (Settings > API keys)',
    'digitalocean-access-token': "Revoke: https://cloud.digitalocean.com/account/api (revoke the OAuth application's authorization)",
    'digitalocean-pat': 'Revoke: https://cloud.digitalocean.com/account/api/tokens',
    'digitalocean-refresh-token': "Revoke: https://cloud.digitalocean.com/account/api (revoke the OAuth application's authorization)",
    'doppler-api-token': 'Revoke: https://dashboard.doppler.com (Settings > Tokens) or `doppler configs tokens revoke`',
    'duffel-api-token': 'Rotate: https://app.duffel.com (Developers > Access tokens)',
    'dynatrace-api-token': 'Revoke: Dynatrace > Access tokens (https://<environment-id>.live.dynatrace.com/ui/access-tokens)',
    'easypost-api-token': 'Rotate: https://www.easypost.com/account/api-keys',
    'easypost-test-api-token': 'Rotate: https://www.easypost.com/account/api-keys',
    'facebook-page-token': 'Revoke: https://developers.facebook.com/tools/debug/accesstoken/ (Invalidate), or reset the app secret in the Meta App Dashboard.',
    'flutterwave-encryption-key': 'Rotate: https://app.flutterwave.com/dashboard/settings/apis',
    'flutterwave-public-key': 'Rotate: https://app.flutterwave.com/dashboard/settings/apis',
    'flutterwave-secret-key': 'Rotate: https://app.flutterwave.com/dashboard/settings/apis',
    'flyio-token': 'Revoke: fly tokens revoke <id>, or https://fly.io/user/personal_access_tokens',
    'frameio-token': 'Revoke: https://developer.frame.io/app/tokens',
    'github-refresh-token': "Revoke: https://github.com/settings/applications (minted by a GitHub App's user-to-server flow)",
    'gitlab-cicd-job-token': 'Job tokens expire when the CI job finishes; cancel the running job/pipeline to invalidate early.',
    'gitlab-deploy-token': 'Revoke: GitLab project/group Settings > Repository > Deploy tokens',
    'gitlab-feature-flag-client-token': 'Rotate: GitLab project Deployments > Feature flags > Configure (regenerate the client token)',
    'gitlab-feed-token': 'Reset: https://gitlab.com/-/user_settings/personal_access_tokens (Feed token > reset)',
    'gitlab-incoming-mail-token': 'Reset: https://gitlab.com/-/user_settings/personal_access_tokens (Incoming email token > reset)',
    'gitlab-kubernetes-agent-token': 'Revoke: GitLab project Operate > Kubernetes clusters > select agent > Access tokens',
    'gitlab-oauth-app-secret': 'Rotate: https://gitlab.com/-/user_settings/applications (Renew secret)',
    'gitlab-pat': 'Revoke: https://gitlab.com/-/user_settings/personal_access_tokens',
    'gitlab-pat-routable': 'Revoke: https://gitlab.com/-/user_settings/personal_access_tokens',
    'gitlab-pipeline-trigger': 'Revoke: project Settings > CI/CD > Pipeline trigger tokens (https://gitlab.com/<project>/-/settings/ci_cd)',
    'gitlab-runner-registration': 'Reset: project/group Settings > CI/CD > Runners, or POST /api/v4/runners/reset_registration_token',
    'gitlab-runner-auth': 'Rotate: POST /api/v4/runners/reset_authentication_token, or unregister and re-register the runner',
    'gitlab-runner-auth-routable': 'Rotate: POST /api/v4/runners/reset_authentication_token, or unregister and re-register the runner',
    'gitlab-scim': 'Regenerate: GitLab group Settings > SAML SSO > SCIM token (https://gitlab.com/groups/<group>/-/saml)',
    'gitlab-session-cookie': 'Revoke: sign out the session at https://gitlab.com/-/user_settings/active_sessions',
    'grafana-api-key': 'Revoke: <your-grafana-url>/org/apikeys (Administration > API keys; migrate to service accounts)',
    'grafana-cloud-token': 'Revoke: https://grafana.com/orgs/<org>/access-policies (Cloud Access Policies > delete the token)',
    'grafana-service-account': 'Revoke: <your-grafana-url>/org/serviceaccounts (Administration > Service accounts)',
    'harness': 'Rotate: https://app.harness.io (My Profile > My API Keys, or Service Account settings > rotate token)',
    'terraform-api-token': 'Revoke: https://app.terraform.io/app/settings/tokens',
    'heroku-api-key': 'Regenerate: https://dashboard.heroku.com/account (API Key > Regenerate), or heroku authorizations:rotate',
    'huggingface-org': "Revoke: https://huggingface.co/settings/tokens (or the organization's settings > Access Tokens)",
    'infracost': 'Rotate: https://dashboard.infracost.io (Org Settings > API keys)',
    'intra42-client-secret': 'Rotate: https://profile.intra.42.fr/oauth/applications (regenerate the app secret)',
    'jwt-base64': 'Invalidate at the issuing service; short-lived tokens may expire naturally.',
    'linear-api-key': 'Revoke: https://linear.app/settings/api',
    'mailgun-private-token': 'Rotate: https://app.mailgun.com/settings/api_security',
    'mailgun-public-key': 'Rotate: https://app.mailgun.com/settings/api_security',
    'mailgun-signing-key': 'Rotate: https://app.mailgun.com/settings/api_security (HTTP webhook signing key)',
    'mapbox-api-token': 'Rotate: https://console.mapbox.com/account/access-tokens/',
    'maxmind-license-key': 'Rotate: https://www.maxmind.com/en/accounts/current/license-key',
    'microsoft-teams-webhook': 'Remove/recreate the Incoming Webhook in the Teams channel (Manage channel -> Connectors / Workflows).',
    'new-relic-browser-token': 'Rotate: https://one.newrelic.com/api-keys',
    'new-relic-insert-key': 'Rotate: https://one.newrelic.com/api-keys',
    'new-relic-user-key': 'Rotate: https://one.newrelic.com/api-keys',
    'notion-api-token': "Revoke: https://www.notion.so/my-integrations (refresh the integration's internal secret)",
    'octopus-deploy-api-key': 'Revoke: <your-octopus-server>/app#/users/me/apiKeys (Profile -> My API Keys)',
    'openshift-user-token': 'Revoke: oc delete useroauthaccesstoken <token-name> on the cluster',
    'perplexity-api-key': 'Revoke: https://www.perplexity.ai/settings/api',
    'plaid-access-token': 'Rotate: POST /item/access_token/invalidate (Plaid API); manage keys at https://dashboard.plaid.com/developers/keys',
    'planetscale-api-token': 'Revoke: https://app.planetscale.com (Organization settings > Service tokens)',
    'planetscale-oauth-token': 'Revoke: https://app.planetscale.com (Organization settings > OAuth applications)',
    'planetscale-password': 'Rotate: pscale password delete / pscale password create, or https://app.planetscale.com (database > Settings > Passwords)',
    'postman-api-key': 'Revoke: https://go.postman.co/settings/me/api-keys',
    'prefect-api-key': 'Revoke: https://app.prefect.cloud/my/api-keys',
    'pulumi-access-token': 'Revoke: https://app.pulumi.com/account/tokens',
    'readme-api-token': 'Rotate: https://dash.readme.com (project Configuration > API Keys)',
    'rubygems-api-key': 'Revoke: https://rubygems.org/profile/api_keys',
    'scalingo-api-token': 'Revoke: https://dashboard.scalingo.com/account/tokens',
    'sendinblue-api-key': 'Revoke: https://app.brevo.com/settings/keys/api',
    'sentry-org-token': 'Revoke: https://sentry.io/settings/ > (organization) > Auth Tokens',
    'sentry-user-token': 'Revoke: https://sentry.io/settings/account/api/auth-tokens/',
    'settlemint-app-token': 'Revoke: https://console.settlemint.com (application > Access tokens)',
    'settlemint-pat': 'Revoke: https://console.settlemint.com (profile > personal access tokens)',
    'settlemint-sat': 'Revoke: https://console.settlemint.com (application > service access tokens)',
    'shippo': 'Rotate: https://apps.goshippo.com/settings/api',
    'shopify-access-token': 'Rotate: Shopify admin > Settings > Apps and sales channels > Develop apps > (app) > API credentials',
    'shopify-custom-access-token': 'Rotate: uninstall and reinstall the custom app in Shopify admin (Settings > Apps and sales channels) to issue a new token',
    'shopify-private-app-token': 'Rotate: Shopify admin > Settings > Apps and sales channels (private apps are deprecated; regenerate credentials or migrate to a custom app)',
    'shopify-shared-secret': 'Rotate: https://partners.shopify.com (app > API access, rotate client secret)',
    'sidekiq-secret': 'Rotate: email support@contribsys.com to reissue your Sidekiq Enterprise license credentials',
    'sidekiq-sensitive-url': 'Rotate: email support@contribsys.com to reissue your Sidekiq Enterprise license credentials',
    'slack-app-token': 'Revoke: https://api.slack.com/apps (app > Basic Information > App-Level Tokens)',
    'slack-config-access-token': 'Revoke: https://api.slack.com/apps (Your App Configuration Tokens panel)',
    'slack-config-refresh-token': 'Revoke: https://api.slack.com/apps (Your App Configuration Tokens panel)',
    'slack-legacy-token': 'Revoke: https://api.slack.com/methods/auth.revoke (legacy tokens are deprecated)',
    'slack-legacy-workspace-token': 'Revoke: https://api.slack.com/methods/auth.revoke (legacy workspace apps are deprecated)',
    'snyk': 'Revoke: https://app.snyk.io/account (regenerate your API token)',
    'square-access-token': "Rotate: https://developer.squareup.com/apps (open the application's Credentials page and replace the token)",
    'telegram-bot-token': 'Revoke: message @BotFather on Telegram and use /revoke (issues a replacement token)',
    'typeform-token': 'Revoke: https://admin.typeform.com/account#/section/tokens',
    'vault-batch-token': 'Batch tokens cannot be revoked directly; revoke the parent token (vault token revoke <parent>) and let the batch token expire at its TTL.',
    'vault-service-token': 'Revoke: vault token revoke <token> (or vault token revoke -self)',
}
